{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation-layout",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-1.6.1-multiplatform-sources.jar",
          "url": "foundation-layout-1.6.1-multiplatform-sources.jar",
          "size": 80606,
          "sha512": "9cbd809eed67a4f74a2ab64394a504c93f4312c3e7f859771df18a76abe52f57b44f119c19e46cfa47da91addbff2b85930d3f337a845b198ec6146e5e39e476",
          "sha256": "d5a743df0bf4320b48e3e36be8d4b261d001b496b188bfc5b280dff292ac295b",
          "sha1": "7621d6b205fbf4eb15a0e250d1cb6ee104f153af",
          "md5": "92efde43c1b17a3ffed886252c421984"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "foundation-layout-1.6.1-versionMetadata.json",
          "size": 23254,
          "sha512": "df2f67ca141bcb937bc4788527f34e488decf588e2d0e27ebfcfa21a7c441aa9b0ae9e27aad9f3ef520a8f8d3f2fb5eba15eb2d26a0f70405561c14a736f7eaa",
          "sha256": "c2f9a108f68328deee573c5dc3d66954dbe2245e6dcfdfd8ae8461a16f430f0f",
          "sha1": "ff2d5c31b912b5291b2990808cf2a234f9147a29",
          "md5": "052db555a47d68ab806968da7897398a"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-metadata-1.6.1.jar",
          "url": "foundation-layout-1.6.1.jar",
          "size": 711,
          "sha512": "c976f2741d710817f385c8a7df959e5a09b90426f82e4fb37d1025e0404e4013c68e13fcbccfbdb93975348e779ea038589c46455f9af9615904bab3b93f824d",
          "sha256": "4e75469751c9d4c464c7d06af283b9737693c20bc4aaf657630bb294c27bbff1",
          "sha1": "2ac53dae14bbb0b6ccb809713e8cf9d1dec92bee",
          "md5": "35c88048156fb6fdb2fa56444ffd0c2d"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "foundation-layout is in atomic group androidx.compose.foundation"
        }
      ],
      "files": [
        {
          "name": "foundation-layout-kotlin-1.6.1-sources.jar",
          "url": "foundation-layout-1.6.1-sources.jar",
          "size": 63053,
          "sha512": "ad5e46e605d42ed819a9f21851bfd1fae8e7a37796c1e0434821afc9209fb169a9ec93fd647acd07b52f2093796b3447280d27faf955078ce522e9661b6c608f",
          "sha256": "06602f717947b74da7040154c05ba7401fe47c26002dddaa29961b438db5dc08",
          "sha1": "edda4f1fde6051d7487be228c1135077e7489eaf",
          "md5": "3bafafdfa342e8c5f9b9ca3b28d067dc"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.6.1/foundation-layout-android-1.6.1.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.6.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.6.1/foundation-layout-android-1.6.1.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.6.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../foundation-layout-android/1.6.1/foundation-layout-android-1.6.1.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-android",
        "version": "1.6.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-desktop/1.6.1/foundation-layout-desktop-1.6.1.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-desktop",
        "version": "1.6.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-desktop/1.6.1/foundation-layout-desktop-1.6.1.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-desktop",
        "version": "1.6.1"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../foundation-layout-desktop/1.6.1/foundation-layout-desktop-1.6.1.module",
        "group": "androidx.compose.foundation",
        "module": "foundation-layout-desktop",
        "version": "1.6.1"
      }
    }
  ]
}