{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-compiler",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "hilt-compiler-1.1.0.jar",
          "url": "hilt-compiler-1.1.0.jar",
          "size": 25341,
          "sha512": "36a2ef3fa61f5befe99bdb13200a31ca6594afe6c28a4efe88e1a518f6115dc3fca817fa6759f3d09c0338c8ca989ba70a69aa45956ed647d59d512bd57b20a2",
          "sha256": "f3ee63a1a6f22810d0a697415765334bd3ffcb9619bc42f06551cefaf97005d9",
          "sha1": "5cccff3df615fb1871f699ce082619ee07e41804",
          "md5": "e9fbed56aba66a4e7ea44515393b4a36"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.9.0-1.0.13"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-compiler-1.1.0.jar",
          "url": "hilt-compiler-1.1.0.jar",
          "size": 25341,
          "sha512": "36a2ef3fa61f5befe99bdb13200a31ca6594afe6c28a4efe88e1a518f6115dc3fca817fa6759f3d09c0338c8ca989ba70a69aa45956ed647d59d512bd57b20a2",
          "sha256": "f3ee63a1a6f22810d0a697415765334bd3ffcb9619bc42f06551cefaf97005d9",
          "sha1": "5cccff3df615fb1871f699ce082619ee07e41804",
          "md5": "e9fbed56aba66a4e7ea44515393b4a36"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-compiler-1.1.0-sources.jar",
          "url": "hilt-compiler-1.1.0-sources.jar",
          "size": 9643,
          "sha512": "94ecd3c417cc0f50483e27d85625c6bee61142a73ffea9568069ddf383366edef672aa9560531d250a565fc476b4bad4dcc17ce56afbb994c17c7b49ccb5e3aa",
          "sha256": "ec009a47903fd872ea309529c319b41e6697987210f8462d86bf8755a75013b5",
          "sha1": "c96b5516eccb58d6891100f9aa75b3a882b4b52b",
          "md5": "8967150b7901589ce62957932cce1fb4"
        }
      ]
    }
  ]
}