{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.sqlite",
    "module": "sqlite-ktx",
    "version": "2.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.4.0.aar",
          "url": "sqlite-ktx-2.4.0.aar",
          "size": 3659,
          "sha512": "1bb3c44cef621510d5ddaebee4142d177ae2248e60ed8257515c73ce9fe72a402f1fdbb2a5d1b914f9605fa6fd70e7110a81e6bafc0298d403acbc179bdb0cc7",
          "sha256": "243f550b06e7573619912611eee6fa7ad6ab03740e17854529053278d5daa7b4",
          "sha1": "5aa1e2addfe6204695fa452eed53da14b01552fa",
          "md5": "bc7e5bf1fb69521939e2e8c7024e78a7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.4.0.aar",
          "url": "sqlite-ktx-2.4.0.aar",
          "size": 3659,
          "sha512": "1bb3c44cef621510d5ddaebee4142d177ae2248e60ed8257515c73ce9fe72a402f1fdbb2a5d1b914f9605fa6fd70e7110a81e6bafc0298d403acbc179bdb0cc7",
          "sha256": "243f550b06e7573619912611eee6fa7ad6ab03740e17854529053278d5daa7b4",
          "sha1": "5aa1e2addfe6204695fa452eed53da14b01552fa",
          "md5": "bc7e5bf1fb69521939e2e8c7024e78a7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.4.0-sources.jar",
          "url": "sqlite-ktx-2.4.0-sources.jar",
          "size": 1472,
          "sha512": "58de3df1d570730581c0e1333f9355f18eb45d8bc0d2b403868a747cc19b67f20f16d1b82077e303b392256d2153c85a93ceea6cef67ff64a6eac4fe0c217780",
          "sha256": "8bc3812b4c267c2165a343ab0db72f2feb7e7238a36adcdbd29eec20154f84c9",
          "sha1": "662cd5258c20344f8dfaae009bb677a9ae882e25",
          "md5": "95e8cf0e4890d80648b2636b6ddf3751"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.4.0"
          },
          "reason": "sqlite-ktx is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-ktx-2.4.0-versionMetadata.json",
          "url": "sqlite-ktx-2.4.0-versionMetadata.json",
          "size": 287,
          "sha512": "c7fa34656dc2af2d39785cb822d9bb5fb59273e1ba52411d56d046ec25984b7b997d544e5c46c26cc31fa43596b7b2f988492fb3fe5445ca2035328e413ecb0f",
          "sha256": "d97365d6760fdd7460e6e1cff1adac38063fec8b1a2f66c6a607ebc27055c190",
          "sha1": "adc59c7bac1346ce2809b96bdd250dd5068b0027",
          "md5": "d305c52e1028c247bd25be592c14b19d"
        }
      ]
    }
  ]
}