{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.48"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-1.1.0.aar",
          "url": "hilt-navigation-1.1.0.aar",
          "size": 3884,
          "sha512": "851ddd90d2136d42b044254a10a3ecbbe322bf57cdfe12504fded49b3b59679be3393e3b298fc803f80a114cd2485720ef0207b77fd746a08c8c5048255561de",
          "sha256": "46a1d12418f77a754fc91c5c28acbf041c78f64ea083f1fa93349d8e43f6ea89",
          "sha1": "c8abfe926091a93c427e7ced78df01fa56b73210",
          "md5": "02e1d0f8773689eae42dbf31bac3faa3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.48"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-1.1.0.aar",
          "url": "hilt-navigation-1.1.0.aar",
          "size": 3884,
          "sha512": "851ddd90d2136d42b044254a10a3ecbbe322bf57cdfe12504fded49b3b59679be3393e3b298fc803f80a114cd2485720ef0207b77fd746a08c8c5048255561de",
          "sha256": "46a1d12418f77a754fc91c5c28acbf041c78f64ea083f1fa93349d8e43f6ea89",
          "sha1": "c8abfe926091a93c427e7ced78df01fa56b73210",
          "md5": "02e1d0f8773689eae42dbf31bac3faa3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-1.1.0-sources.jar",
          "url": "hilt-navigation-1.1.0-sources.jar",
          "size": 1857,
          "sha512": "c5b9c1ad24273b3701ce61dae6d2a61591c67589bd403e63b04f4a59c59dba9e88453ac5936efa4f5d5e0aa11333841e995e5b562172bf900759cf5b415e6979",
          "sha256": "ef41a00d473f45b14d513058d0d4c51114df8c3ea2249d7e2d29e6d05dcc5fad",
          "sha1": "3ac307cbdcb6c029df8c3b775dca05d4f700561e",
          "md5": "e646191db1eefe79913bf491203abf2d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "hilt-navigation-1.1.0-versionMetadata.json",
          "url": "hilt-navigation-1.1.0-versionMetadata.json",
          "size": 310,
          "sha512": "e971d8a07279be88c8ce18eb6bde94ae5f8210f6e0de26b3e3725454ebd64d61d39504b615adce51bac7876d0033454e900501b016ea9187fda8aa0815290cda",
          "sha256": "98b169d52bc554459dd86cee405820745df437026cdc3bcf16bf9512ab999905",
          "sha1": "ba142f41dadf92e82fc48a5ffc569c85ecfc66b3",
          "md5": "98cbbe48c3b39e78d592c5a0ac77dc65"
        }
      ]
    }
  ]
}