{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-core/1.6.2/kotlinx-serialization-core-1.6.2.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-core",
    "version": "1.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.6.2.jar",
          "url": "kotlinx-serialization-core-jvm-1.6.2.jar",
          "size": 419740,
          "sha512": "b5a49fe2a97616b6b2854b876e7af6a6a7b6cc74cde97ffa59a334ea479a28a5043e5b2bcfdea3af9e4bbc1826e6920d1cdd3d026c24671313564dbdbbca8b83",
          "sha256": "8e6fc04e1a2efd2acbbc5503a1dc9d988166f99e4f1f51ef6b91c3a52077bdb1",
          "sha1": "384c2492c987f1d92bfa186580de058c284b2ad9",
          "md5": "22d4706b09b9e068fbd3d97233f07865"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.6.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.6.2.jar",
          "url": "kotlinx-serialization-core-jvm-1.6.2.jar",
          "size": 419740,
          "sha512": "b5a49fe2a97616b6b2854b876e7af6a6a7b6cc74cde97ffa59a334ea479a28a5043e5b2bcfdea3af9e4bbc1826e6920d1cdd3d026c24671313564dbdbbca8b83",
          "sha256": "8e6fc04e1a2efd2acbbc5503a1dc9d988166f99e4f1f51ef6b91c3a52077bdb1",
          "sha1": "384c2492c987f1d92bfa186580de058c284b2ad9",
          "md5": "22d4706b09b9e068fbd3d97233f07865"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-core-jvm-1.6.2-sources.jar",
          "url": "kotlinx-serialization-core-jvm-1.6.2-sources.jar",
          "size": 104626,
          "sha512": "b1d112612f58680851e5a22e407b6b0a84192ab63b20e0bb61e20a37b1939eea00713458ffb243a3720985395f9fe08a8c7e8361fe7fa58c36c5c742ddf9f6d1",
          "sha256": "78d6f251829c04b8b4ba695ac5c5a4738e701ade88e05ecaf6404d7a68dfaf1b",
          "sha1": "57f7ef1d5572b44fd7534b33adf2100b13c3c681",
          "md5": "e010340a8d3cda7ec154efa120032df9"
        }
      ]
    }
  ]
}
