{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation-compose",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0.aar",
          "url": "hilt-navigation-compose-1.1.0.aar",
          "size": 4842,
          "sha512": "484151efcf8120985cec5d1728b45616500e6742ac7d7c3b6ff3f33360f7f4764ee643157dd720f23ffcc6025363dfccd0e1a45faeb39288af3e1d66ff058d55",
          "sha256": "2231d45cd97c0dece44cb85ab82e72debdbff6bfa429493e8c74649d12192f45",
          "sha1": "3279eaf1336d7ffee21ef65df4f496c5772f75e2",
          "md5": "01adf6a372414894348a68dfd26d2472"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-navigation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0.aar",
          "url": "hilt-navigation-compose-1.1.0.aar",
          "size": 4842,
          "sha512": "484151efcf8120985cec5d1728b45616500e6742ac7d7c3b6ff3f33360f7f4764ee643157dd720f23ffcc6025363dfccd0e1a45faeb39288af3e1d66ff058d55",
          "sha256": "2231d45cd97c0dece44cb85ab82e72debdbff6bfa429493e8c74649d12192f45",
          "sha1": "3279eaf1336d7ffee21ef65df4f496c5772f75e2",
          "md5": "01adf6a372414894348a68dfd26d2472"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0-sources.jar",
          "url": "hilt-navigation-compose-1.1.0-sources.jar",
          "size": 1939,
          "sha512": "9d953f2dc5dc6f0a85594451d05ed095ede99bb770d0e10c586a6b350ef54ac11c67d8deb135fbe2fd2fae2663ecf704a1aa3bdb28ab67c7272f4f6b23b26496",
          "sha256": "0880d8f7d6cadbfa9d6515d34a2c7bd4320ef833ed5e59787298e0d59877e057",
          "sha1": "b540805d6c2c35b8d17f903f888a201ec17b507a",
          "md5": "39e0bf2b799330f47ff1198a0cd32035"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.1.0-versionMetadata.json",
          "url": "hilt-navigation-compose-1.1.0-versionMetadata.json",
          "size": 389,
          "sha512": "fe59a7d072eef272a2f99a80693de5a91d2ee8044a046ed7a723919f5a0a82e27f9be3fd781745a28489935d6a3dee3178eee4f228cc753d4ddb3991ca210275",
          "sha256": "fa0d7902852e64ee150f2fb0acac47acf649f5864cb205fc4229229e28f58337",
          "sha1": "cf3232464d42571b8e0b1fc435f47e8c0a5e6cf6",
          "md5": "b19c54557c13673118d2d01a07c64439"
        }
      ]
    }
  ]
}