ARG RUNTIME_IMAGE
FROM ${RUNTIME_IMAGE}

WORKDIR /opt/securechat
COPY --chown=10001:10001 signaling-server/build/libs/signaling-server-all.jar /opt/securechat/app.jar

USER 10001:10001
EXPOSE 8080

ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=70", "-XX:+ExitOnOutOfMemoryError", "-XX:-CreateCoredumpOnCrash", "-XX:+DisableAttachMechanism", "-XX:ErrorFile=/dev/null", "-XX:HeapDumpPath=/dev/null", "-Djava.io.tmpdir=/tmp", "-jar", "/opt/securechat/app.jar"]
