{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.7.6.aar",
          "url": "navigation-runtime-ktx-2.7.6.aar",
          "size": 2114,
          "sha512": "479d872eb706aef34c6493a564c32c59983eba3d7242f79e15a4e80ca8140c114c4ba612be06a27af5f1fb9617ebebd0a11a377f14ffb3889494376150307db3",
          "sha256": "996fa26573f78515a8d2f52eba1fb24719070864a7315be712621a574455e756",
          "sha1": "b41134cb853acff7f2a8034dac311bc76d53972e",
          "md5": "93e7351541b19399ec98a449678cd07a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "Mirror navigation-runtime dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.7.6.aar",
          "url": "navigation-runtime-ktx-2.7.6.aar",
          "size": 2114,
          "sha512": "479d872eb706aef34c6493a564c32c59983eba3d7242f79e15a4e80ca8140c114c4ba612be06a27af5f1fb9617ebebd0a11a377f14ffb3889494376150307db3",
          "sha256": "996fa26573f78515a8d2f52eba1fb24719070864a7315be712621a574455e756",
          "sha1": "b41134cb853acff7f2a8034dac311bc76d53972e",
          "md5": "93e7351541b19399ec98a449678cd07a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.7.6-sources.jar",
          "url": "navigation-runtime-ktx-2.7.6-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.7.6-versionMetadata.json",
          "url": "navigation-runtime-ktx-2.7.6-versionMetadata.json",
          "size": 2839,
          "sha512": "7217a5c665e4d0a448aed41692f2864d65cdaa3e8ff6ad3b60830069ffa5ceef900e245a2b5e8405489b7d84a400df6cabca2ea06f913833ee7414182e179dbd",
          "sha256": "974a7ade0887f9b1a8142ac91041d064dd0792183a6a19ceb77a51215fc5f302",
          "sha1": "3002de81bae1156c51ab2e1a935b5becc7fb81c1",
          "md5": "20d32ff0cd1696e8714c00d84df9aedd"
        }
      ]
    }
  ]
}