{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-icons-core/1.6.1/material-icons-core-1.6.1.module",
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.6.1.aar",
          "size": 823515,
          "sha512": "fe28c0f0c47088633d46646f89894431ff90d3be4734c0e54ee14824166a57f596ef08194f9b923ba9a560b267aa111d6f4ccb4bce0f604db7198d0aa444abb7",
          "sha256": "63b0137ec668b7d4effa3e83f0c0cea68297f369c012aeec04e80be54bc25247",
          "sha1": "be6998192dcc7b06531e18c909030ed16b401681",
          "md5": "a35f13d730fcce009818e7fb79ea3556"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-release.aar",
          "url": "material-icons-core-android-1.6.1.aar",
          "size": 823515,
          "sha512": "fe28c0f0c47088633d46646f89894431ff90d3be4734c0e54ee14824166a57f596ef08194f9b923ba9a560b267aa111d6f4ccb4bce0f604db7198d0aa444abb7",
          "sha256": "63b0137ec668b7d4effa3e83f0c0cea68297f369c012aeec04e80be54bc25247",
          "sha1": "be6998192dcc7b06531e18c909030ed16b401681",
          "md5": "a35f13d730fcce009818e7fb79ea3556"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-icons-core is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-icons-core-android-1.6.1-sources.jar",
          "url": "material-icons-core-android-1.6.1-sources.jar",
          "size": 284048,
          "sha512": "2803312f6e4dfb1b2501b44f47eb72fd02212e41a18c5dcbec7b7e280612b486d23b72d50688a2fb3776b1582ae63ec923fd3f39bdbc4e951a779dc133495f64",
          "sha256": "b3f1be7fda4d13a6d938bb918275ddc143e9d6a2007727f284778480526f5f16",
          "sha1": "e518df0d8a19c3833f72a24ff667853015e340fd",
          "md5": "6f8dfe229b864de0e1deaa71ad0c1434"
        }
      ]
    }
  ]
}