{
  "formatVersion": "1.1",
  "component": {
    "group": "io.coil-kt",
    "module": "coil",
    "version": "2.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "coil-2.6.0.aar",
          "url": "coil-2.6.0.aar",
          "size": 7771,
          "sha512": "fbfdb1574819a01ec3428349a1eaca76046669a3470ba9c1fa0c463d33607d26b482549155f0fb161db307950f6e52d523636e8043c456252418a92ae9b93c1f",
          "sha256": "d78fa2c72fc31d98320b82ed06524c73e99e88a329f0731c4a31190ccfa4dfb1",
          "sha1": "4fa04428e2d9544d56731a3fd06bd063885589a9",
          "md5": "164930b8c0155a2005e5ccba4e3015b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.coil-kt",
          "module": "coil-base",
          "version": {
            "requires": "2.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "coil-2.6.0.aar",
          "url": "coil-2.6.0.aar",
          "size": 7771,
          "sha512": "fbfdb1574819a01ec3428349a1eaca76046669a3470ba9c1fa0c463d33607d26b482549155f0fb161db307950f6e52d523636e8043c456252418a92ae9b93c1f",
          "sha256": "d78fa2c72fc31d98320b82ed06524c73e99e88a329f0731c4a31190ccfa4dfb1",
          "sha1": "4fa04428e2d9544d56731a3fd06bd063885589a9",
          "md5": "164930b8c0155a2005e5ccba4e3015b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-2.6.0-sources.jar",
          "url": "coil-2.6.0-sources.jar",
          "size": 2946,
          "sha512": "6e16951d6f27f98f0963a50e8d420cf3b93ae9bfbb55770a6cb4b3ad0106be21b80ac3a9b248a1fde3d3abcc8ee1e0208630ea0c110ebb83647595e150ce6f6a",
          "sha256": "2d73133de75104871dae6555732a2fcfc517b08eea7f747b8fb2b7f105bc1c66",
          "sha1": "937a2d5a82528330e0a0c6b09142703a4a0874ae",
          "md5": "84fa9cb5c3cef4c23b6dbf3ff7b11d99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "coil-2.6.0-javadoc.jar",
          "url": "coil-2.6.0-javadoc.jar",
          "size": 281287,
          "sha512": "8e4411416531583ab1e19503c476ad66dd1949cfe7b2fc6152f7930b1396ecf9fe54858ca099c032799d4d9ac97919f0dd982b7cc1257092781a42b59944cec2",
          "sha256": "f7010de283587a19f67d11961b7e41555bd5ddbb899db81baf38b157b7715f56",
          "sha1": "871b2f8e81bdbbefa1bcb21cca6e06334ea77f91",
          "md5": "3d943e1efaf80db58688f672e1c1cb2a"
        }
      ]
    }
  ]
}
