{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-1.2.0-multiplatform-sources.jar",
          "url": "material3-1.2.0-multiplatform-sources.jar",
          "size": 472980,
          "sha512": "5cd0d34e0920f48f5f25e02d92789e08a0681cb70484160c7ed48e2ae753abc1c2dadd69f547df75e415c6bfe6d4ca6c6d1d28c39d8da62c86094edb40a626d1",
          "sha256": "a7659858059b7a5158bdb31afc36d7172d2a55625279d7b7b8fb57d8f8a3589d",
          "sha1": "bb2bba0aa81fd83857ac1642b95fcafa2423f9ac",
          "md5": "aed80f8fba990fc99c9b423f563cd2d1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material3-1.2.0-versionMetadata.json",
          "size": 166046,
          "sha512": "2ecaed769a26f124d632028324a60654cc2ef8977a048fcac2787017fc23a0f055c382599f3dea9b1d0a765850d81da726b5138fc79eec5388e2312911d5e48c",
          "sha256": "cb8d4889b4c3b200ae68d94b5e2a314e1e32c3d259f59fc7b5985355e2271bfe",
          "sha1": "a6f279e6475003dc85608d7f93a01a7683bb2d9a",
          "md5": "c3846904e4bb5d94fd8fb7cd7f1bfb48"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-metadata-1.2.0.jar",
          "url": "material3-1.2.0.jar",
          "size": 784,
          "sha512": "bb74b8e1ec3e136aa27836738002a0ab52dd0a9ea4c421fc53e14c7e3b90972184556cd3c6b95eb31f3f4309c1ee490915526ad591cddf80001c30b015a9bb90",
          "sha256": "5c6576dc36130ac4e4f95296f5b27a56363ed2e0e626b9dc619b6125972be95e",
          "sha1": "72056ca0a6dfc44d840a97706e2bd19dfab60f1f",
          "md5": "1a8d0b624acedb8ac289eeebcd324369"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "material3 is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-kotlin-1.2.0-sources.jar",
          "url": "material3-1.2.0-sources.jar",
          "size": 407404,
          "sha512": "fd1a2863ff027058b64ad8472e761b437a2c19e330f100734283dfbb7277b8fbdd392a714569c805f5e62216e0ef441e0f07d8a2f4f06247fb6ad6b6a912a00d",
          "sha256": "c5a542fd7f23f31aa2f677047c9d02695f7b902a6dc06e7d302df4a2238550c1",
          "sha1": "773a014e2b918fe9ee28bab28c8fbba93b976d27",
          "md5": "ac09b550f37734fef54f641c58689ce0"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.2.0/material3-android-1.2.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.2.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.2.0/material3-android-1.2.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.2.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-android/1.2.0/material3-android-1.2.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-android",
        "version": "1.2.0"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.2.0/material3-desktop-1.2.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.2.0"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.2.0/material3-desktop-1.2.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.2.0"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-desktop/1.2.0/material3-desktop-1.2.0.module",
        "group": "androidx.compose.material3",
        "module": "material3-desktop",
        "version": "1.2.0"
      }
    }
  ]
}