import 'dart:convert';
import 'dart:io';

/// Mechanically imports the unchanged Kotlin Android string catalog into ARB.
/// Run from flutter_securechat/: dart tool/import_android_strings.dart
void main() {
  final sourceRoot = Directory('../app/src/main/res');
  if (!sourceRoot.existsSync()) {
    stderr.writeln('Android resource directory was not found.');
    exitCode = 2;
    return;
  }
  final locales = <String, String>{
    'en': 'values-en/strings.xml',
    'tr': 'values/strings.xml',
    'de': 'values-de/strings.xml',
    'ar': 'values-ar/strings.xml',
  };
  final output = Directory('lib/l10n')..createSync(recursive: true);
  for (final entry in locales.entries) {
    final strings = _parse(
      File('${sourceRoot.path}/${entry.value}').readAsStringSync(),
    );
    strings.addAll(_flutterAdditions[entry.key]!);
    final arb = <String, Object?>{'@@locale': entry.key};
    for (final item in strings.entries) {
      final converted = _convertPlaceholders(item.value);
      arb[item.key] = converted.text;
      if (converted.placeholders.isNotEmpty) {
        arb['@${item.key}'] = {
          'description': 'Migrated from Android string ${item.key}.',
          'placeholders': converted.placeholders,
        };
      }
    }
    File('${output.path}/app_${entry.key}.arb').writeAsStringSync(
      const JsonEncoder.withIndent('  ').convert(arb) + '\n',
      flush: true,
    );
  }
}

const _flutterAdditions = <String, Map<String, String>>{
  'tr': {
    'conversations_title': 'Sohbetler',
    'conversations_search': 'Sohbetlerde ara',
    'nav_chats': 'Sohbet',
    'nav_calls': 'Arama',
    'nav_contacts': 'Rehber',
    'chat_e2ee': 'Uçtan uca şifreli',
    'archive_remove': 'Arşivden çıkar',
    'profile_photo_change': 'Profil fotoğrafını değiştir',
    'settings_watermark_desc': 'Elçim filigranını göster',
    'settings_scheduled_enabled_desc': 'Arka plan gönderimlerini etkinleştir',
    'settings_local_data_desc': 'Mesajlar, kişiler, medya ve ayarlar',
    'settings_account_data_desc': 'Sunucu hesabı ve bu cihazdaki tüm veriler',
    'settings_logout': 'Çıkış yap',
    'settings_notification_preview_desc': 'Kilit ekranı bildirim önizlemesi',
    'settings_default_notification_sound': 'Varsayılan bildirim sesi',
    'settings_silent': 'Sessiz',
    'settings_share_last_seen': 'Son görülmeyi paylaş',
    'settings_screen_protection': 'Ekran koruması etkin',
    'camera': 'Kamera',
    'gallery': 'Galeri',
    'profile_photo_remove': 'Fotoğrafı kaldır',
    'settings_delete_local_data': 'Tüm yerel verileri sil',
    'settings_delete_account': 'Hesabı kalıcı olarak sil',
    'settings_delete_account_body':
        'Sunucu hesabınız ve bu cihazdaki tüm veriler silinecek. Bu işlem geri alınamaz.',
    'theme_system': 'Sistem',
    'theme_light': 'Açık',
    'theme_dark': 'Koyu',
    'settings_content_hidden': 'Mesaj içeriği gizli',
    'settings_content_visible': 'İçerik görünür',
    'settings_privacy': 'Gizlilik',
    'settings_last_seen_hidden': 'Son görülme paylaşılmıyor',
    'settings_last_seen_shared': 'Son görülme paylaşılıyor',
    'settings_fullscreen_ios_desc':
        'iOS sistem alanlarını korur; kenardan kenara görünüm uygulanır',
    'settings_fullscreen_android_desc':
        'Android sistem çubuklarını uygulama içinde gizle',
    'settings_auto_download': 'Otomatik indirme',
    'settings_auto_download_desc': 'Wi-Fi ve mobil veri kuralları',
    'settings_call_readiness': 'Arama hazırlığı',
    'settings_call_readiness_desc': 'Pil, bildirim ve kilit ekranı izinleri',
    'settings_bulk_message': 'Toplu mesaj',
    'settings_bulk_message_desc': 'Birden fazla sohbete güvenli gönderim',
    'settings_storage_desc': 'Medya ve sohbet kullanımı',
    'settings_presence_immediate_desc':
        'Değişiklik çevrimiçi durum protokolüne hemen iletilir',
    'settings_screen_protection_desc':
        'Android ekran yakalamayı engeller; iOS uygulama değiştiricide içeriği örter.',
    'group_not_found': 'Grup bulunamadı.',
    'group_admin_only': 'Sadece yöneticiler yazabilir',
    'group_announcement_desc': 'Grubu duyuru kanalı olarak kullan',
    'mute': 'Sessize al',
    'chat_lock': 'Sohbet kilidi',
    'chat_lock_desc': 'Cihaz doğrulamasıyla erişim',
    'export_history': 'Dışa aktarma geçmişi',
    'make_admin': 'Yönetici yap',
    'no_contacts_to_add': 'Eklenebilecek kayıtlı kişi yok.',
    'confirmation': 'Onay',
    'confirm': 'Onayla',
    'background_unavailable': 'Arka plan servisi kullanılamıyor.',
    'edit_mode': 'Düzenleme modu',
    'repeat_once': 'Tek',
    'repeat_daily': 'Her gün',
    'repeat_custom': 'Özel',
    'weekdays_short': 'Pzt,Sal,Çar,Per,Cum,Cmt,Paz',
    'delivery_time': 'Gönderim saati',
    'message_content': 'Mesaj içeriği',
    'recipients': 'Alıcılar',
    'recipient_required': 'En az bir kişi veya grup seçin',
    'schedule': 'Planla',
    'update': 'Güncelle',
    'no_scheduled_messages': 'Henüz planlı mesaj yok.',
    'schedule_saved': 'Planlı mesaj kaydedildi.',
    'form_incomplete': 'Form eksik.',
    'over_wifi': 'Wi-Fi üzerinden',
    'over_cellular': 'Hücresel veri üzerinden',
    'photos': 'Fotoğraflar',
    'videos': 'Videolar',
    'documents': 'Belgeler',
    'cellular_limit': 'Hücresel üst sınırı: %1\$d MB',
    'no_chats_yet': 'Henüz sohbet yok',
    'storage_summary': '%1\$d mesaj · %2\$d dosya · %3\$s',
    'clear_media': 'Medyayı temizle',
    'clear_media_body':
        '“%1\$s” sohbetindeki medya ve dosya mesajları silinecek. Metin mesajları korunur.',
    'no_exports_yet': 'Henüz dışa aktarma yapılmadı',
    'message_count': '%1\$d mesaj',
    'entire_chat': 'Tüm sohbet',
    'admin_only_screen': 'Bu ekran sadece grup yöneticilerine açıktır',
    'bulk_unavailable': 'Toplu gönderim kullanılamıyor.',
    'select_all': 'Tümünü seç',
    'group': 'Grup',
    'send_to_recipients': '%1\$d alıcıya gönder',
    'bulk_result': '%1\$d gönderildi, %2\$d başarısız.',
    'encrypted_backup': 'Şifreli Yedekleme',
    'backup_explanation':
        'Sohbetler, kişiler, çağrı kayıtları, planlı mesajlar ve uçtan uca şifreleme durumu parola ile korunan .elbk dosyasına kaydedilir. Oturum erişim anahtarları yedeğe eklenmez.',
    'create_backup': 'Yeni yedek oluştur',
    'restore_backup_file': 'Yedek dosyasını geri yükle',
    'backups_on_device': 'Bu cihazdaki yedekler',
    'no_local_backups': 'Henüz yerel yedek yok',
    'backup_password': 'Yedek parolası',
    'backup_unavailable': 'Yedekleme hizmeti kullanılamıyor.',
    'save_encrypted_backup': 'Şifreli yedeği kaydet',
    'backup_created': 'Yedek şifreli olarak oluşturuldu.',
    'backup_create_failed': 'Yedek oluşturulamadı: %1\$s',
    'backup_restored': 'Yedek geri yüklendi.',
    'wrong_password_attempts': 'Parola yanlış. %1\$d deneme kaldı.',
    'backup_deleted_after_attempts':
        'Beş yanlış deneme sonrası yedek dosyası silindi.',
    'backup_delete_failed_after_attempts':
        'Deneme sınırı doldu; dosya platform tarafından silinemedi.',
    'password': 'Parola',
    'password_min_length': 'En az 8 karakter',
    'password_repeat': 'Parola tekrar',
    'password_too_short': 'Parola en az 8 karakter olmalı.',
    'password_mismatch': 'Parolalar eşleşmiyor.',
    'restore': 'Geri yükle',
    'no_call_history': 'Henüz arama kaydı yok.',
    'video_call': 'Görüntülü ara',
    'voice_call': 'Sesli ara',
    'outgoing': 'Giden',
    'incoming': 'Gelen',
    'video': 'görüntülü',
    'voice': 'sesli',
    'missed': 'Cevapsız',
    'rejected': 'Reddedildi',
    'busy': 'Meşgul',
    'failed': 'Başarısız',
    'call_description': '%1\$s %2\$s arama%3\$s',
    'recheck_status': 'Durumu yeniden denetle',
    'calls_ready': 'Aramalar için hazırsınız',
    'calls_readiness_missing':
        'Aramaların gecikmemesi için eksikleri tamamlayın',
    'battery_optimization_desc':
        'Data-only push ve arka plan işlerinin Doze gecikmesini azaltır',
    'fullscreen_call_notification': 'Tam ekran arama bildirimi',
    'fullscreen_call_notification_desc':
        'Android 14+ kilit ekranı arama görünümü',
    'notification_permission': 'Bildirim izni',
    'notification_permission_desc': 'Mesaj ve gelen arama bildirimleri',
    'overlay_permission': 'Diğer uygulamaların üstünde göster',
    'overlay_permission_desc': 'Android arka plan arama ekranı',
    'ios_call_readiness_note':
        'iOS’ta pil optimizasyonu, tam ekran intent ve overlay uygulama tarafından değiştirilemez. Gelen çağrı uyandırması APNs/CallKit ve sistem politikalarına bağlıdır.',
    'secure_communication': 'Güvenli Haberleşme',
    'onboarding_private_subtitle': 'Mesajlarınız yalnızca sizin aranızda',
    'onboarding_private_body':
        'Her mesaj cihazınızda şifrelenir; sunucu içeriği göremez.',
    'onboarding_direct_call': 'Doğrudan arama',
    'onboarding_webrtc_subtitle': 'Sesli ve görüntülü WebRTC',
    'onboarding_webrtc_body':
        'Bire bir aramalar doğrudan, büyük grup aramaları Janus SFU üzerinden çalışır.',
    'onboarding_privacy_control': 'Tam gizlilik kontrolü',
    'onboarding_you_decide': 'Siz karar verirsiniz',
    'onboarding_privacy_body':
        'Tek gösterim, süreli mesaj, ekran koruması ve grup export politikası.',
    'skip': 'Atla',
    'lets_start': 'Başlayalım',
    'continue_action': 'Devam et',
    'notifications': 'Bildirimler',
    'notifications_permission_reason': 'Yeni mesaj ve aramalar için.',
    'contacts_permission_reason': 'Kişileri yalnızca hash ile keşfetmek için.',
    'microphone': 'Mikrofon',
    'microphone_permission_reason': 'Sesli ve görüntülü aramalar için.',
    'camera_permission_reason': 'Görüntülü aramalar için.',
    'permissions_required': 'Birkaç izin gerekiyor',
    'permissions_intro':
        'İstediklerinizi şimdi verebilir, kalanlarını daha sonra ayarlardan açabilirsiniz.',
    'grant_permission': 'İzin ver',
    'chat_not_found': 'Sohbet bulunamadı.',
    'contact_info': 'Kişi Bilgileri',
    'starred_messages': 'Yıldızlı Mesajlar',
    'media': 'Medya',
    'disappearing_messages': 'Süreli mesajlar',
    'contact_note': 'Kişiye not',
    'tap_to_add_note': 'Not eklemek için dokun',
    'no_records': 'Kayıt bulunamadı',
    'add_contact_note': 'Kişiye not ekle',
    'off': 'Kapalı',
    'hours': '%1\$d saat',
    'days': '%1\$d gün',
    'files_selected': '%1\$d dosya seçildi',
    'add_caption': 'Açıklama ekle...',
    'view_once': 'Tek gösterim',
    'view_once_protected': 'Tek gösterimlik · ekran korumalı',
    'share': 'Paylaş',
    'tap_to_close_view_once': 'Kapatmak için dokunun · bir daha açılamaz',
    'file_open_failed': 'Dosya açılamadı: %1\$s',
    'file_share_failed': 'Dosya paylaşılamadı: %1\$s',
    'file': 'Dosya',
    'open_with_app': 'Uygulamayla aç',
    'media_not_found': 'Medya dosyası bulunamadı',
    'call_service_unavailable': 'Çağrı hizmeti başlatılamadı.',
    'locked_chat': 'Kilitli Sohbet',
    'disable_export': 'Dışa aktarmayı kapat',
    'enable_export': 'Dışa aktarmayı aç',
    'clear_chat': 'Sohbeti temizle',
    'read_only_announcement':
        'Bu grup sadece yöneticilerin yazabildiği bir duyuru kanalıdır.',
    'no_matching_messages': 'Eşleşen mesaj bulunamadı',
    'cancel_selection': 'Seçimi iptal et',
    'messages_selected': '%1\$d mesaj seçildi',
    'forward_selected': 'Seçilenleri ilet',
    'record_voice_message': 'Sesli mesaj kaydet',
    'poll': 'Anket',
    'add_reaction': 'Tepki ver',
    'remove_star': 'Yıldızı kaldır',
    'add_star': 'Yıldızla',
    'unpin': 'Sabitlemeyi kaldır',
    'pin': 'Sabitle',
    'choose_reaction': 'Tepki seç',
    'delete_for_everyone': 'Herkesten sil',
    'clear_chat_confirm': 'Sohbet temizlensin mi?',
    'clear_chat_body': 'Bu cihazdaki tüm mesajlar kalıcı olarak silinir.',
    'voice_message': 'Sesli mesaj',
    'recording_start_failed': 'Kayıt başlatılamadı',
    'recording_paused': 'Kayıt duraklatıldı',
    'recording_active': 'Kayıt sürüyor',
    'send': 'Gönder',
    'poll_load_failed': 'Anket yüklenemedi',
    'single_choice': 'Tekli seçim',
    'multiple_choice': 'Çoklu seçim',
    'total_votes': 'Toplam %1\$d oy',
    'message_info': 'Mesaj Bilgisi',
    'sent': 'Gönderildi',
    'read': 'Okundu',
    'delivered': 'İletildi',
    'send_failed_no_plaintext':
        'Gönderim başarısız. Plaintext fallback uygulanmadı.',
    'forward_to_chat': 'Sohbete ilet',
    'read_only_chat': 'Salt okunur sohbet',
    'participant_count': '%1\$d katılımcı',
    'create_poll': 'Anket Oluştur',
    'question': 'Soru',
    'option_number': 'Seçenek %1\$d',
    'add_option': 'Seçenek ekle',
    'member_export_permission': 'Üyelerin kopyalama ve dışa aktarma yetkisi',
    'admin_change_only': 'Yalnızca yönetici değiştirebilir',
    'remove_member_named': '%1\$s gruptan çıkarılsın mı?',
    'leave_group_confirm': 'Bu gruptan ayrılmak istiyor musunuz?',
    'archive': 'Arşiv',
    'remove_favorite': 'Favorilerden çıkar',
    'add_favorite': 'Favoriye ekle',
    'mark_read': 'Okundu işaretle',
    'mark_unread': 'Okunmadı işaretle',
    'delete_chat_body':
        '%1\$s sohbeti ve bu cihazdaki mesajları kalıcı olarak silinsin mi?',
    'reject': 'Reddet',
    'answer': 'Cevapla',
    'unmute': 'Sesi aç',
    'speaker': 'Hoparlör',
    'flip_camera': 'Çevir',
    'end_call': 'Bitir',
    'call_preparing': 'Arama hazırlanıyor…',
    'incoming_call': 'Gelen arama',
    'ringing': 'Çalıyor…',
    'connecting': 'Bağlanıyor…',
    'reconnecting': 'Yeniden bağlanıyor…',
    'call_ended': 'Arama sona erdi',
    'call_rejected': 'Arama reddedildi',
    'connection_failed': 'Bağlantı kurulamadı',
    'voice_service_unavailable': 'Sesli mesaj hizmeti başlatılamadı.',
    'voice_encrypting': 'Sesli mesaj şifrelenip gönderiliyor…',
    'voice_sent': 'Sesli mesaj gönderildi.',
    'voice_send_failed': 'Sesli mesaj gönderilemedi: %1\$s',
    'file_transfer_unavailable': 'Dosya aktarım hizmeti başlatılamadı.',
    'media_pick_failed': 'Medya seçilemedi: %1\$s',
    'media_encrypting': 'Medya şifrelenip gönderiliyor…',
    'media_send_failed': 'Medya gönderilemedi: %1\$s',
    'media_sent': '%1\$d medya şifreli olarak gönderildi.',
    'media_failed': '%1\$d medya gönderilemedi: %2\$s',
    'poll_unavailable': 'Anket hizmeti kullanılamıyor.',
    'poll_sent': 'Anket gönderildi.',
    'poll_send_failed': 'Anket gönderilemedi.',
    'vote_send_failed': 'Oy güvenli olarak gönderilemedi.',
    'pin_failed': 'Sabitleme yetkisi yok veya sinyal gönderilemedi.',
    'forward_service_unavailable': 'Mesaj iletme hizmeti başlatılamadı.',
    'forward_encrypting': '%1\$d mesaj %2\$s için yeniden şifreleniyor…',
    'forward_encryption_result':
        '%1\$d mesaj iletildi; %2\$d mesaj şifrelenemedi ve gönderilmedi.',
    'forward_sent': '%1\$d mesaj iletildi.',
    'forward_partial': '%1\$d mesaj iletildi; %2\$d mesaj gönderilemedi.',
    'reaction_failed': 'Tepki gönderilemedi.',
    'edit_failed': 'Mesaj düzenlenemedi.',
    'delete_signal_failed': 'Silme bildirimi gönderilemedi.',
    'export_unavailable': 'Dışa aktarma kullanılamıyor.',
    'chat_exported': 'Sohbet dışa aktarıldı.',
    'group_policy_unavailable': 'Grup ilkesi kullanılamıyor.',
    'export_disabled': 'Dışa aktarma kapatıldı.',
    'export_enabled': 'Dışa aktarma açıldı.',
    'chat_unmuted': 'Sohbet sesi açıldı.',
    'chat_muted': 'Sohbet sessize alındı.',
    'invalid_voice_recording': 'Geçerli bir ses kaydı oluşturulamadı.',
    'audio_not_found': 'Ses dosyası bulunamadı',
    'audio_play_failed': 'Ses kaydı oynatılamadı',
    'opened': 'Açıldı',
    'view_once_photo': 'Tek gösterimlik fotoğraf',
    'media_no_longer_available': 'Bu medya artık açılamaz',
    'tap_to_open': 'Açmak için dokunun',
    'attachment': 'Ek ekle',
    'dialpad': 'Tuş takımını aç',
    'remove_option': 'Seçeneği kaldır',
    'auth_unavailable': 'Kimlik doğrulama hizmeti yapılandırılmamış.',
    'rate_limit_seconds': 'Çok fazla istek. %1\$d saniye bekleyin.',
    'chat_cleared': 'Sohbet temizlendi.',
    'no_registered_contacts':
        'Kayıtlı kişi bulunamadı. Rehber izni verip yenilemeyi deneyin.',
  },
  'en': {
    'conversations_title': 'Chats',
    'conversations_search': 'Search chats',
    'nav_chats': 'Chats',
    'nav_calls': 'Calls',
    'nav_contacts': 'Contacts',
    'chat_e2ee': 'End-to-end encrypted',
    'archive_remove': 'Unarchive',
    'profile_photo_change': 'Change profile photo',
    'settings_watermark_desc': 'Show the Elçim watermark',
    'settings_scheduled_enabled_desc': 'Enable background delivery',
    'settings_local_data_desc': 'Messages, contacts, media and settings',
    'settings_account_data_desc': 'Server account and all data on this device',
    'settings_logout': 'Log out',
    'settings_notification_preview_desc': 'Lock-screen notification preview',
    'settings_default_notification_sound': 'Default notification sound',
    'settings_silent': 'Silent',
    'settings_share_last_seen': 'Share last seen',
    'settings_screen_protection': 'Screen protection enabled',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'profile_photo_remove': 'Remove photo',
    'settings_delete_local_data': 'Delete all local data',
    'settings_delete_account': 'Permanently delete account',
    'settings_delete_account_body':
        'Your server account and all data on this device will be deleted. This cannot be undone.',
    'theme_system': 'System',
    'theme_light': 'Light',
    'theme_dark': 'Dark',
    'settings_content_hidden': 'Message content hidden',
    'settings_content_visible': 'Content visible',
    'settings_privacy': 'Privacy',
    'settings_last_seen_hidden': 'Last seen is not shared',
    'settings_last_seen_shared': 'Last seen is shared',
    'settings_fullscreen_ios_desc':
        'iOS keeps system areas visible and uses an edge-to-edge layout',
    'settings_fullscreen_android_desc':
        'Hide Android system bars inside the app',
    'settings_auto_download': 'Automatic download',
    'settings_auto_download_desc': 'Wi-Fi and mobile data rules',
    'settings_call_readiness': 'Call readiness',
    'settings_call_readiness_desc':
        'Battery, notification and lock-screen permissions',
    'settings_bulk_message': 'Bulk message',
    'settings_bulk_message_desc': 'Send securely to multiple chats',
    'settings_storage_desc': 'Media and chat usage',
    'settings_presence_immediate_desc':
        'Changes are sent to the online presence protocol immediately',
    'settings_screen_protection_desc':
        'Android blocks screen capture; iOS covers content in the app switcher.',
    'group_not_found': 'Group not found.',
    'group_admin_only': 'Only admins can send messages',
    'group_announcement_desc': 'Use the group as an announcement channel',
    'mute': 'Mute',
    'chat_lock': 'Chat lock',
    'chat_lock_desc': 'Access with device authentication',
    'export_history': 'Export history',
    'make_admin': 'Make admin',
    'no_contacts_to_add': 'No saved contacts can be added.',
    'confirmation': 'Confirmation',
    'confirm': 'Confirm',
    'background_unavailable': 'Background service is unavailable.',
    'edit_mode': 'Edit mode',
    'repeat_once': 'Once',
    'repeat_daily': 'Daily',
    'repeat_custom': 'Custom',
    'weekdays_short': 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
    'delivery_time': 'Delivery time',
    'message_content': 'Message content',
    'recipients': 'Recipients',
    'recipient_required': 'Select at least one person or group',
    'schedule': 'Schedule',
    'update': 'Update',
    'no_scheduled_messages': 'No scheduled messages yet.',
    'schedule_saved': 'Scheduled message saved.',
    'form_incomplete': 'The form is incomplete.',
    'over_wifi': 'Over Wi-Fi',
    'over_cellular': 'Over cellular data',
    'photos': 'Photos',
    'videos': 'Videos',
    'documents': 'Documents',
    'cellular_limit': 'Cellular limit: %1\$d MB',
    'no_chats_yet': 'No chats yet',
    'storage_summary': '%1\$d messages · %2\$d files · %3\$s',
    'clear_media': 'Clear media',
    'clear_media_body':
        'Media and file messages in “%1\$s” will be deleted. Text messages are retained.',
    'no_exports_yet': 'No exports yet',
    'message_count': '%1\$d messages',
    'entire_chat': 'Entire chat',
    'admin_only_screen': 'This screen is available only to group admins',
    'bulk_unavailable': 'Bulk sending is unavailable.',
    'select_all': 'Select all',
    'group': 'Group',
    'send_to_recipients': 'Send to %1\$d recipients',
    'bulk_result': '%1\$d sent, %2\$d failed.',
    'encrypted_backup': 'Encrypted Backup',
    'backup_explanation':
        'Chats, contacts, call logs, scheduled messages and end-to-end encryption state are stored in a password-protected .elbk file. Session access keys are excluded.',
    'create_backup': 'Create a new backup',
    'restore_backup_file': 'Restore a backup file',
    'backups_on_device': 'Backups on this device',
    'no_local_backups': 'No local backups yet',
    'backup_password': 'Backup password',
    'backup_unavailable': 'Backup service is unavailable.',
    'save_encrypted_backup': 'Save encrypted backup',
    'backup_created': 'Encrypted backup created.',
    'backup_create_failed': 'Could not create backup: %1\$s',
    'backup_restored': 'Backup restored.',
    'wrong_password_attempts': 'Wrong password. %1\$d attempts remaining.',
    'backup_deleted_after_attempts':
        'The backup file was deleted after five incorrect attempts.',
    'backup_delete_failed_after_attempts':
        'Attempt limit reached; the platform could not delete the file.',
    'password': 'Password',
    'password_min_length': 'At least 8 characters',
    'password_repeat': 'Repeat password',
    'password_too_short': 'Password must be at least 8 characters.',
    'password_mismatch': 'Passwords do not match.',
    'restore': 'Restore',
    'no_call_history': 'No call history yet.',
    'video_call': 'Video call',
    'voice_call': 'Voice call',
    'outgoing': 'Outgoing',
    'incoming': 'Incoming',
    'video': 'video',
    'voice': 'voice',
    'missed': 'Missed',
    'rejected': 'Rejected',
    'busy': 'Busy',
    'failed': 'Failed',
    'call_description': '%1\$s %2\$s call%3\$s',
    'recheck_status': 'Check status again',
    'calls_ready': 'You are ready for calls',
    'calls_readiness_missing': 'Complete missing items to prevent call delays',
    'battery_optimization_desc':
        'Reduces Doze delays for data-only push and background work',
    'fullscreen_call_notification': 'Full-screen call notification',
    'fullscreen_call_notification_desc': 'Android 14+ lock-screen call view',
    'notification_permission': 'Notification permission',
    'notification_permission_desc': 'Message and incoming call notifications',
    'overlay_permission': 'Display over other apps',
    'overlay_permission_desc': 'Android background call screen',
    'ios_call_readiness_note':
        'On iOS, battery optimization, full-screen intent and overlay cannot be changed by the app. Incoming-call wake-up depends on APNs/CallKit and system policies.',
    'secure_communication': 'Secure Communication',
    'onboarding_private_subtitle': 'Your messages stay between you',
    'onboarding_private_body':
        'Every message is encrypted on your device; the server cannot read its content.',
    'onboarding_direct_call': 'Direct calls',
    'onboarding_webrtc_subtitle': 'Voice and video over WebRTC',
    'onboarding_webrtc_body':
        'One-to-one calls connect directly; large group calls use the Janus SFU.',
    'onboarding_privacy_control': 'Complete privacy control',
    'onboarding_you_decide': 'You decide',
    'onboarding_privacy_body':
        'View once, disappearing messages, screen protection and group export policy.',
    'skip': 'Skip',
    'lets_start': 'Get started',
    'continue_action': 'Continue',
    'notifications': 'Notifications',
    'notifications_permission_reason': 'For new messages and calls.',
    'contacts_permission_reason': 'To discover people using hashes only.',
    'microphone': 'Microphone',
    'microphone_permission_reason': 'For voice and video calls.',
    'camera_permission_reason': 'For video calls.',
    'permissions_required': 'A few permissions are required',
    'permissions_intro':
        'Grant the permissions you want now; you can enable the rest later in settings.',
    'grant_permission': 'Grant permission',
    'chat_not_found': 'Chat not found.',
    'contact_info': 'Contact Info',
    'starred_messages': 'Starred Messages',
    'media': 'Media',
    'disappearing_messages': 'Disappearing messages',
    'contact_note': 'Contact note',
    'tap_to_add_note': 'Tap to add a note',
    'no_records': 'No records found',
    'add_contact_note': 'Add contact note',
    'off': 'Off',
    'hours': '%1\$d hours',
    'days': '%1\$d days',
    'files_selected': '%1\$d files selected',
    'add_caption': 'Add a caption...',
    'view_once': 'View once',
    'view_once_protected': 'View once · screen protected',
    'share': 'Share',
    'tap_to_close_view_once': 'Tap to close · cannot be opened again',
    'file_open_failed': 'Could not open file: %1\$s',
    'file_share_failed': 'Could not share file: %1\$s',
    'file': 'File',
    'open_with_app': 'Open with app',
    'media_not_found': 'Media file not found',
    'call_service_unavailable': 'Call service could not be started.',
    'locked_chat': 'Locked Chat',
    'disable_export': 'Disable export',
    'enable_export': 'Enable export',
    'clear_chat': 'Clear chat',
    'read_only_announcement':
        'This group is an announcement channel where only admins can post.',
    'no_matching_messages': 'No matching messages found',
    'cancel_selection': 'Cancel selection',
    'messages_selected': '%1\$d messages selected',
    'forward_selected': 'Forward selected',
    'record_voice_message': 'Record voice message',
    'poll': 'Poll',
    'add_reaction': 'Add reaction',
    'remove_star': 'Remove star',
    'add_star': 'Star',
    'unpin': 'Unpin',
    'pin': 'Pin',
    'choose_reaction': 'Choose reaction',
    'delete_for_everyone': 'Delete for everyone',
    'clear_chat_confirm': 'Clear this chat?',
    'clear_chat_body':
        'All messages on this device will be permanently deleted.',
    'voice_message': 'Voice message',
    'recording_start_failed': 'Could not start recording',
    'recording_paused': 'Recording paused',
    'recording_active': 'Recording',
    'send': 'Send',
    'poll_load_failed': 'Could not load poll',
    'single_choice': 'Single choice',
    'multiple_choice': 'Multiple choice',
    'total_votes': '%1\$d total votes',
    'message_info': 'Message Info',
    'sent': 'Sent',
    'read': 'Read',
    'delivered': 'Delivered',
    'send_failed_no_plaintext':
        'Sending failed. Plaintext fallback was not used.',
    'forward_to_chat': 'Forward to chat',
    'read_only_chat': 'Read-only chat',
    'participant_count': '%1\$d participants',
    'create_poll': 'Create Poll',
    'question': 'Question',
    'option_number': 'Option %1\$d',
    'add_option': 'Add option',
    'member_export_permission': 'Members may copy and export',
    'admin_change_only': 'Only an admin can change this',
    'remove_member_named': 'Remove %1\$s from the group?',
    'leave_group_confirm': 'Do you want to leave this group?',
    'archive': 'Archive',
    'remove_favorite': 'Remove from favorites',
    'add_favorite': 'Add to favorites',
    'mark_read': 'Mark as read',
    'mark_unread': 'Mark as unread',
    'delete_chat_body':
        'Permanently delete the %1\$s chat and its messages from this device?',
    'reject': 'Reject',
    'answer': 'Answer',
    'unmute': 'Unmute',
    'speaker': 'Speaker',
    'flip_camera': 'Flip',
    'end_call': 'End',
    'call_preparing': 'Preparing call…',
    'incoming_call': 'Incoming call',
    'ringing': 'Ringing…',
    'connecting': 'Connecting…',
    'reconnecting': 'Reconnecting…',
    'call_ended': 'Call ended',
    'call_rejected': 'Call rejected',
    'connection_failed': 'Could not connect',
    'voice_service_unavailable': 'Voice message service could not be started.',
    'voice_encrypting': 'Encrypting and sending voice message…',
    'voice_sent': 'Voice message sent.',
    'voice_send_failed': 'Could not send voice message: %1\$s',
    'file_transfer_unavailable': 'File transfer service could not be started.',
    'media_pick_failed': 'Could not select media: %1\$s',
    'media_encrypting': 'Encrypting and sending media…',
    'media_send_failed': 'Could not send media: %1\$s',
    'media_sent': '%1\$d media items sent encrypted.',
    'media_failed': '%1\$d media items failed: %2\$s',
    'poll_unavailable': 'Poll service is unavailable.',
    'poll_sent': 'Poll sent.',
    'poll_send_failed': 'Could not send poll.',
    'vote_send_failed': 'Vote could not be sent securely.',
    'pin_failed': 'No pin permission or signaling failed.',
    'forward_service_unavailable':
        'Message forwarding service could not start.',
    'forward_encrypting': 'Re-encrypting %1\$d messages for %2\$s…',
    'forward_encryption_result':
        '%1\$d messages forwarded; %2\$d could not be encrypted and were not sent.',
    'forward_sent': '%1\$d messages forwarded.',
    'forward_partial': '%1\$d messages forwarded; %2\$d failed.',
    'reaction_failed': 'Could not send reaction.',
    'edit_failed': 'Could not edit message.',
    'delete_signal_failed': 'Could not send deletion signal.',
    'export_unavailable': 'Export is unavailable.',
    'chat_exported': 'Chat exported.',
    'group_policy_unavailable': 'Group policy is unavailable.',
    'export_disabled': 'Export disabled.',
    'export_enabled': 'Export enabled.',
    'chat_unmuted': 'Chat unmuted.',
    'chat_muted': 'Chat muted.',
    'invalid_voice_recording': 'A valid voice recording could not be created.',
    'audio_not_found': 'Audio file not found',
    'audio_play_failed': 'Could not play voice recording',
    'opened': 'Opened',
    'view_once_photo': 'View-once photo',
    'media_no_longer_available': 'This media can no longer be opened',
    'tap_to_open': 'Tap to open',
    'attachment': 'Add attachment',
    'dialpad': 'Open dial pad',
    'remove_option': 'Remove option',
    'auth_unavailable': 'Authentication service is not configured.',
    'rate_limit_seconds': 'Too many requests. Wait %1\$d seconds.',
    'chat_cleared': 'Chat cleared.',
    'no_registered_contacts':
        'No registered contacts found. Grant contacts permission and refresh.',
  },
  'de': {
    'conversations_title': 'Chats',
    'conversations_search': 'Chats durchsuchen',
    'nav_chats': 'Chats',
    'nav_calls': 'Anrufe',
    'nav_contacts': 'Kontakte',
    'chat_e2ee': 'Ende-zu-Ende verschlüsselt',
    'archive_remove': 'Archivierung aufheben',
    'profile_photo_change': 'Profilbild ändern',
    'settings_watermark_desc': 'Elçim-Wasserzeichen anzeigen',
    'settings_scheduled_enabled_desc': 'Hintergrundversand aktivieren',
    'settings_local_data_desc':
        'Nachrichten, Kontakte, Medien und Einstellungen',
    'settings_account_data_desc': 'Serverkonto und alle Daten auf diesem Gerät',
    'settings_logout': 'Abmelden',
    'settings_notification_preview_desc':
        'Benachrichtigungsvorschau auf dem Sperrbildschirm',
    'settings_default_notification_sound': 'Standard-Benachrichtigungston',
    'settings_silent': 'Lautlos',
    'settings_share_last_seen': 'Zuletzt online teilen',
    'settings_screen_protection': 'Bildschirmschutz aktiviert',
    'camera': 'Kamera',
    'gallery': 'Galerie',
    'profile_photo_remove': 'Foto entfernen',
    'settings_delete_local_data': 'Alle lokalen Daten löschen',
    'settings_delete_account': 'Konto dauerhaft löschen',
    'settings_delete_account_body':
        'Dein Serverkonto und alle Daten auf diesem Gerät werden gelöscht. Dies kann nicht rückgängig gemacht werden.',
    'theme_system': 'System',
    'theme_light': 'Hell',
    'theme_dark': 'Dunkel',
    'settings_content_hidden': 'Nachrichteninhalt ausgeblendet',
    'settings_content_visible': 'Inhalt sichtbar',
    'settings_privacy': 'Datenschutz',
    'settings_last_seen_hidden': 'Zuletzt online wird nicht geteilt',
    'settings_last_seen_shared': 'Zuletzt online wird geteilt',
    'settings_fullscreen_ios_desc':
        'iOS behält Systembereiche bei und verwendet ein randloses Layout',
    'settings_fullscreen_android_desc':
        'Android-Systemleisten in der App ausblenden',
    'settings_auto_download': 'Automatischer Download',
    'settings_auto_download_desc': 'WLAN- und Mobilfunkregeln',
    'settings_call_readiness': 'Anrufbereitschaft',
    'settings_call_readiness_desc':
        'Akku-, Benachrichtigungs- und Sperrbildschirmberechtigungen',
    'settings_bulk_message': 'Sammelnachricht',
    'settings_bulk_message_desc': 'Sicher an mehrere Chats senden',
    'settings_storage_desc': 'Medien- und Chatnutzung',
    'settings_presence_immediate_desc':
        'Änderungen werden sofort an das Anwesenheitsprotokoll gesendet',
    'settings_screen_protection_desc':
        'Android blockiert Bildschirmaufnahmen; iOS verdeckt Inhalte im App-Umschalter.',
  },
  'ar': {
    'conversations_title': 'الدردشات',
    'conversations_search': 'البحث في الدردشات',
    'nav_chats': 'الدردشات',
    'nav_calls': 'المكالمات',
    'nav_contacts': 'جهات الاتصال',
    'chat_e2ee': 'مشفّرة من طرف إلى طرف',
    'archive_remove': 'إلغاء الأرشفة',
    'profile_photo_change': 'تغيير صورة الملف الشخصي',
    'settings_watermark_desc': 'إظهار علامة Elçim المائية',
    'settings_scheduled_enabled_desc': 'تمكين الإرسال في الخلفية',
    'settings_local_data_desc': 'الرسائل وجهات الاتصال والوسائط والإعدادات',
    'settings_account_data_desc': 'حساب الخادم وجميع البيانات على هذا الجهاز',
    'settings_logout': 'تسجيل الخروج',
    'settings_notification_preview_desc': 'معاينة الإشعارات على شاشة القفل',
    'settings_default_notification_sound': 'صوت الإشعار الافتراضي',
    'settings_silent': 'صامت',
    'settings_share_last_seen': 'مشاركة آخر ظهور',
    'settings_screen_protection': 'حماية الشاشة مفعّلة',
    'camera': 'الكاميرا',
    'gallery': 'المعرض',
    'profile_photo_remove': 'إزالة الصورة',
    'settings_delete_local_data': 'حذف جميع البيانات المحلية',
    'settings_delete_account': 'حذف الحساب نهائيًا',
    'settings_delete_account_body':
        'سيتم حذف حساب الخادم وجميع البيانات على هذا الجهاز. لا يمكن التراجع عن ذلك.',
    'theme_system': 'النظام',
    'theme_light': 'فاتح',
    'theme_dark': 'داكن',
    'settings_content_hidden': 'محتوى الرسالة مخفي',
    'settings_content_visible': 'المحتوى ظاهر',
    'settings_privacy': 'الخصوصية',
    'settings_last_seen_hidden': 'آخر ظهور غير مشارك',
    'settings_last_seen_shared': 'آخر ظهور مشارك',
    'settings_fullscreen_ios_desc':
        'يحافظ iOS على مناطق النظام ويستخدم تخطيطًا ممتدًا للحواف',
    'settings_fullscreen_android_desc': 'إخفاء أشرطة نظام Android داخل التطبيق',
    'settings_auto_download': 'التنزيل التلقائي',
    'settings_auto_download_desc': 'قواعد Wi-Fi وبيانات الهاتف',
    'settings_call_readiness': 'جاهزية المكالمات',
    'settings_call_readiness_desc': 'أذونات البطارية والإشعارات وشاشة القفل',
    'settings_bulk_message': 'رسالة جماعية',
    'settings_bulk_message_desc': 'إرسال آمن إلى عدة دردشات',
    'settings_storage_desc': 'استخدام الوسائط والدردشات',
    'settings_presence_immediate_desc':
        'تُرسل التغييرات فورًا إلى بروتوكول حالة الاتصال',
    'settings_screen_protection_desc':
        'يمنع Android التقاط الشاشة، ويغطي iOS المحتوى في مبدّل التطبيقات.',
  },
};

Map<String, String> _parse(String xml) {
  final values = <String, String>{};
  final pattern = RegExp(r'<string\s+name="([^"]+)"[^>]*>([\s\S]*?)</string>');
  for (final match in pattern.allMatches(xml)) {
    values[match.group(1)!] = _decodeXml(match.group(2)!.trim());
  }
  return values;
}

String _decodeXml(String value) => value
    .replaceAll('&lt;', '<')
    .replaceAll('&gt;', '>')
    .replaceAll('&quot;', '"')
    .replaceAll('&apos;', "'")
    .replaceAll('&amp;', '&')
    .replaceAll(r"\'", "'");

_Converted _convertPlaceholders(String value) {
  final placeholders = <String, Object?>{};
  final converted = value.replaceAllMapped(RegExp(r'%(\d+)\$([ds])'), (match) {
    final name = 'arg${match.group(1)}';
    placeholders[name] = {'type': match.group(2) == 'd' ? 'num' : 'String'};
    return '{$name}';
  });
  return _Converted(converted, placeholders);
}

class _Converted {
  const _Converted(this.text, this.placeholders);
  final String text;
  final Map<String, Object?> placeholders;
}
