{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.7.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.7.6.aar",
          "url": "navigation-runtime-2.7.6.aar",
          "size": 129028,
          "sha512": "b190a2b4fc56ef95193ad4c2fb865cafe4bdef74c6ff4f4a1db63d521eafb662623e90e1e7abb33eb0b68c57b87ca5630b8955ee12abb9c524234e9455cd640e",
          "sha256": "dbad2d4bcaafb00d0de6bc6fcd0a1887156a7bafe33ca2cbe58341edc0d43afb",
          "sha1": "4cb5888903afcbf2ef96e7420b3f1998e4431a97",
          "md5": "75f534483901c30d4bca5c320473366a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.7.6.aar",
          "url": "navigation-runtime-2.7.6.aar",
          "size": 129028,
          "sha512": "b190a2b4fc56ef95193ad4c2fb865cafe4bdef74c6ff4f4a1db63d521eafb662623e90e1e7abb33eb0b68c57b87ca5630b8955ee12abb9c524234e9455cd640e",
          "sha256": "dbad2d4bcaafb00d0de6bc6fcd0a1887156a7bafe33ca2cbe58341edc0d43afb",
          "sha1": "4cb5888903afcbf2ef96e7420b3f1998e4431a97",
          "md5": "75f534483901c30d4bca5c320473366a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.7.6-sources.jar",
          "url": "navigation-runtime-2.7.6-sources.jar",
          "size": 48381,
          "sha512": "03a9326553f4a2c4ab393c5983877ed85607aca62f3c102bbcef289168073055b777542a74f71642a133cf9c08018e1af3de692edf70545c2113c21c0836ae6b",
          "sha256": "41a4c9a1ecebba1285d36c11558707744c1aafbdffb16aaf837ba30f5df05445",
          "sha1": "136cdad1fe68a293a074fbdfd06242a939269ef9",
          "md5": "b0ef436e6475818abaace59af2cf8263"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.7.6"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.7.6-versionMetadata.json",
          "url": "navigation-runtime-2.7.6-versionMetadata.json",
          "size": 13434,
          "sha512": "9f489d9f9511290d0bfe0886033b3883dffc4a01c5ccaf60227025f8b5558879c6efbfc4a1a67a8ac52fbc070621a9a488aaae76479d36a0838ffc3025159e4d",
          "sha256": "6b83e027926c9ce6f7d072f35813562b93371146d7597326d1b197b5fbfb903d",
          "sha1": "327550a03417af39e27b98d1c87f966b95f801d1",
          "md5": "8c5c65d70e94942bbd0e5612df25d897"
        }
      ]
    }
  ]
}