{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "7093604"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.1.0.aar",
          "url": "biometric-1.1.0.aar",
          "size": 194748,
          "sha512": "824c2e6855bb97bf8bc207a3469edcd58a5ca5f6292ad481973d81ce23e15f01095002393b7338deaa78f451ea3bf2603bbccc53ddce880da907496dcb1fa401",
          "sha256": "270c7b7d99942d5ec1dd88594e4648feb33d8e31d8c3c2ab2321d49d9abdfc1f",
          "sha1": "3d4d3a881cc8cbeee5bf9dd6a4e8326f0e4b44cd",
          "md5": "d0f242864af8614e1516743c8090f21d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.1.0.aar",
          "url": "biometric-1.1.0.aar",
          "size": 194748,
          "sha512": "824c2e6855bb97bf8bc207a3469edcd58a5ca5f6292ad481973d81ce23e15f01095002393b7338deaa78f451ea3bf2603bbccc53ddce880da907496dcb1fa401",
          "sha256": "270c7b7d99942d5ec1dd88594e4648feb33d8e31d8c3c2ab2321d49d9abdfc1f",
          "sha1": "3d4d3a881cc8cbeee5bf9dd6a4e8326f0e4b44cd",
          "md5": "d0f242864af8614e1516743c8090f21d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-1.1.0-sources.jar",
          "url": "biometric-1.1.0-sources.jar",
          "size": 48939,
          "sha512": "a855050689b6ae63a0f434668b58ad9c9dbc198dc69503e838d76040e5b49dd0c55dc40522aa8e66e9fe8458b411814c4223625153e3014d87f1c95776c8b744",
          "sha256": "a34841717766cd97c36f708763ead26c79a9721129ffd87c57c99fea10a8f9e0",
          "sha1": "0150ff7f1122d0f9f8b0c222334bbd3b7aa82c7f",
          "md5": "d36b724f9c3818ddde2e84b4cdc7440c"
        }
      ]
    }
  ]
}
