{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-1.6.1-multiplatform-sources.jar",
          "url": "ui-1.6.1-multiplatform-sources.jar",
          "size": 839444,
          "sha512": "acbd98fbf098c290dc270b603c9cfe1ea663eae6315cdf3073073fe9e65241b0dad0875f443da9c858b7b408a9256bc5b7aa7a7697e06ed2483992376008545f",
          "sha256": "647f2209bc8a2c68e4714ca80af1f30314d14528ca3f50aa1f16f0b4108ac308",
          "sha1": "624a68854c5a3bc1bd3709739238ee77505e68ef",
          "md5": "f33b3eb0b42c5ab4dbe054e91855f7f5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "ui-1.6.1-versionMetadata.json",
          "size": 176263,
          "sha512": "ba26dfd815d619f60f7c2b4bf7d94b1e97b59ad02424f4452f5156c4897ff97db8316a82941ddf3478ab05e59a3f75ac377f73f9be4b2980d2a83443bb52d0b1",
          "sha256": "97d1fa708402bb4c0eac64445c3b2a0763646f4f8b9385af94b2d43b36abee21",
          "sha1": "b7d8a28774144e222318cc423005ba514e64e9b5",
          "md5": "beda7e031f3894691d01454010852421"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-metadata-1.6.1.jar",
          "url": "ui-1.6.1.jar",
          "size": 775,
          "sha512": "08820dd5f0cbb2e77db290bc75a7e7dab013d4b6adb54c6af1e4142a2e401e719fc90c351f4784ffef17e1c4bf2b0f02aef1ea09da80fc2b72a2731af3cc4c19",
          "sha256": "b25acd07331b59c6ddf49b639f7322552c31b25e03a83f97f04ec4a3bacd8d25",
          "sha1": "20f60d7008b634d88aea2c49f40acaaa5f3c9e0c",
          "md5": "8fb1b9a77cdd8a2a011deef6d7b31c12"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "ui is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-kotlin-1.6.1-sources.jar",
          "url": "ui-1.6.1-sources.jar",
          "size": 443403,
          "sha512": "e568c6301a76e8b6bfe4c7873be559949e82a8679578cf4d5c6858393c33d5d4e1d28b60d79e9e74ea507506b66776318ca4f844430e0c56cb5c4e1a75834ca5",
          "sha256": "d4a7733f4240d949d2ca7d614f2cc767dbf4ded1f728a0d46f241872511ea25f",
          "sha1": "9b7bc2a4588158b52ae56b480cb7494a9d74908a",
          "md5": "6ef5d3276f3def5de33534e398b9661c"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-android/1.6.1/ui-android-1.6.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-android",
        "version": "1.6.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-android/1.6.1/ui-android-1.6.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-android",
        "version": "1.6.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../ui-android/1.6.1/ui-android-1.6.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-android",
        "version": "1.6.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-desktop/1.6.1/ui-desktop-1.6.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-desktop",
        "version": "1.6.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-desktop/1.6.1/ui-desktop-1.6.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-desktop",
        "version": "1.6.1"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ui-desktop/1.6.1/ui-desktop-1.6.1.module",
        "group": "androidx.compose.ui",
        "module": "ui-desktop",
        "version": "1.6.1"
      }
    }
  ]
}