{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material-ripple/1.6.1/material-ripple-1.6.1.module",
    "group": "androidx.compose.material",
    "module": "material-ripple",
    "version": "1.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.6.1.aar",
          "size": 73206,
          "sha512": "03e26e7a217da3012bc0aa07499cbbb206ffe6023fd5850e6a7203045da47d3713e7d2943cb16473fb80b554b9ae2942d06a6b3f317a9d58446500ed5bd51eee",
          "sha256": "c5bba91dac1fe66a4f96630b03ccf888f15c5afbfe641f1bd2c466dc8b15735e",
          "sha1": "b00045482d0b998be9d580e0b17e0b7d686e37c3",
          "md5": "de60cf3c79d6987651896a3443f0ce24"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-ripple-release.aar",
          "url": "material-ripple-android-1.6.1.aar",
          "size": 73206,
          "sha512": "03e26e7a217da3012bc0aa07499cbbb206ffe6023fd5850e6a7203045da47d3713e7d2943cb16473fb80b554b9ae2942d06a6b3f317a9d58446500ed5bd51eee",
          "sha256": "c5bba91dac1fe66a4f96630b03ccf888f15c5afbfe641f1bd2c466dc8b15735e",
          "sha1": "b00045482d0b998be9d580e0b17e0b7d686e37c3",
          "md5": "de60cf3c79d6987651896a3443f0ce24"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.6.1"
          },
          "reason": "material-ripple is in atomic group androidx.compose.material"
        }
      ],
      "files": [
        {
          "name": "material-ripple-android-1.6.1-sources.jar",
          "url": "material-ripple-android-1.6.1-sources.jar",
          "size": 23223,
          "sha512": "f95da268f90a671eaa6ff66c79b66f431197fc7e7582386e64a914658b490ac08abce189cbb5322db4aed203b6857a34fef1967ff43035330937ae00edd14a5c",
          "sha256": "6bc29ab177ee9c9db20b06ea1fdbbed612f9a9fae0ec6885fb6d86781fbad7f3",
          "sha1": "5658994fca2cfab39445d8960d9609737b5f71be",
          "md5": "44bd50910312abb6a6d10efa9dcb7976"
        }
      ]
    }
  ]
}